"""
Django settings for config_rfq project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

BASE_DIR = Path(__file__).resolve().parent.parent

GOOGLE_CREDENTIALS = os.path.join(BASE_DIR, 'config/rfq-automation-495519-18ae3cd45c97.json')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-+vqz2mpad(o$r*=df@rmflbxu$q(e@)!^(i^4z)+ik6v&tj1c5')

# [PATCH - CRÍTICO] DEBUG ya NO está hardcodeado en True.
# Con DEBUG=True, Django guarda en RAM cada query SQL ejecutada
# (connection.queries) durante toda la vida del proceso, y nunca la libera.
# En un sistema que procesa cientos de archivos por día, esto por sí solo
# puede explicar gran parte del consumo de RAM que estás viendo.
#
# En Railway: NO definas la variable de entorno DEBUG (o ponla en "False").
# En tu máquina local: crea un .env con DEBUG=True si lo necesitas para desarrollar.
DEBUG = os.getenv('DEBUG', 'False').strip().lower() == 'true'

ALLOWED_HOSTS = ['sistemarfq-production.up.railway.app', 'localhost', '127.0.0.1']

# Añade esta sección crucial para que Django acepte las peticiones POST de Railway:
CSRF_TRUSTED_ORIGINS = [
    'https://sistemarfq-production.up.railway.app',
]

# O si prefieres abrirlo por completo para asegurar:
# ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'RFQ',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config_rfq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config_rfq.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import dj_database_url

# Buscamos explícitamente MYSQL_URL con guion bajo, tal como sale en tu panel de Railway
DATABASE_URL = os.getenv('MYSQL_URL') or os.getenv('MYSQLURL') or os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Si detecta la URL en la nube de Railway, configura el diccionario dinámicamente
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600
        )
    }
    # Forzar el motor de MySQL en producción si la librería tiene dudas con el esquema
    if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
        DATABASES['default']['ENGINE'] = 'django.db.backends.mysql'
else:
    # Tu base de datos local para cuando trabajas offline en tu computadora
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'noticias',
            'USER': 'root',
            'PASSWORD': '1234sk',
            'HOST': 'localhost',
            'PORT': '3307',
        }
    }

# --- CONFIGURACIÓN DE CELERY ---
# En Railway usará REDIS_URL, localmente usará el localhost
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# --- CONCURRENCIA: seguimos limitando a 1 tarea a la vez ---
# (esto está bien tal como lo tenías; el problema no era la concurrencia)
CELERY_WORKER_CONCURRENCY = 1
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# [PATCH - IMPORTANTE] Antes: CELERY_WORKER_MAX_TASKS_PER_CHILD = 1
#
# Con valor 1, Celery MATA el proceso worker después de CADA archivo procesado.
# El problema: PaddleOCR y SentenceTransformer('all-MiniLM-L6-v2') son modelos
# de cientos de MB que se cargan desde cero cada vez que arranca un proceso
# nuevo (ver ocr_service.py y embedding_matcher.py). Esto significa que estás
# pagando el costo de "cargar el modelo pesado en RAM" en CADA archivo, en vez
# de una sola vez por proceso.
#
# Subimos esto a 25: el proceso procesa 25 archivos, reutilizando los modelos
# ya cargados en memoria (ahorro grande de RAM y de tiempo), y luego se
# recicla para evitar fugas de memoria acumuladas de librerías C externas
# (PaddleOCR / opencv / cadquery), que sí pueden tener leaks graduales.
CELERY_WORKER_MAX_TASKS_PER_CHILD = 25

# [PATCH - IMPORTANTE] Antes: CELERY_WORKER_MAX_MEMORY_PER_CHILD = 250000 (250MB)
#
# PaddleOCR + SentenceTransformer + cadquery/trimesh cargados juntos en el
# mismo proceso muy probablemente superan 250MB solo en modelos, sin contar
# el archivo que se está procesando. Con este límite tan bajo, Railway puede
# estar matando y reiniciando el worker constantemente, lo que a su vez
# provoca que los modelos se recarguen una y otra vez (ciclo que CONSUME
# más RAM acumulada en el tiempo, no menos).
#
# Subimos el límite a 900MB (ajusta según lo que veas en Railway con
# `celery -A config_rfq worker --loglevel=info` y monitoreo real).
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 900000  # 900 MB



# --- API KEYS SEGURAS ---
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "django-insecure-+vqz2mpad(o$r*=df@rmflbxu$q(e@)!^(i^4z)+ik6v&tj1c5")



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Habilitar almacenamiento eficiente y compresión con WhiteNoise
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 52428800 bytes = 50 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800

# [PATCH - RECOMENDADO] Reactivamos esta línea (estaba comentada).
# Esto obliga a Django a escribir archivos subidos grandes directamente a
# disco temporal en vez de mantenerlos completos en RAM durante el request,
# protegiendo la memoria del proceso web (gunicorn).
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# [PATCH - INTEGRACIÓN DE BUCKET R2] ------------------------------------
#
# En vez de pasar archivos por Base64 a través de Redis (el patrón que
# causaba el consumo alto de RAM), ahora el proceso web guarda el archivo
# directamente en un bucket R2, y el worker de Celery lo descarga de ahí
# usando solo una "key" (string corto), no el contenido completo.
#
# Esto también resuelve el problema de "no pudimos usar volumen compartido":
# ya no lo necesitas, porque el bucket ES el medio compartido entre el
# servicio web y el worker.
#
# Requisitos (agrega esto a requirements.txt):
#   django-storages
#   boto3
#
# Variables de entorno que debes configurar en Railway (web Y worker):
#   R2_ACCESS_KEY_ID
#   R2_SECRET_ACCESS_KEY
#   R2_BUCKET_NAME
#   R2_ENDPOINT_URL      -> https://<account_id>.r2.cloudflarestorage.com
#
# Si estas variables NO están definidas (por ejemplo en tu máquina local),
# el sistema sigue usando el FileSystemStorage de siempre, sin romper tu
# entorno de desarrollo.

USE_R2_STORAGE = bool(os.getenv('R2_BUCKET_NAME'))

if USE_R2_STORAGE:
    INSTALLED_APPS += ['storages']

    AWS_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('R2_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('R2_ENDPOINT_URL')
    AWS_S3_ADDRESSING_STYLE = 'virtual'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_REGION_NAME = 'auto'  # R2 usa 'auto' como región
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True  # URLs firmadas con expiración, bucket privado
    AWS_S3_FILE_OVERWRITE = True

    STORAGES['default']['BACKEND'] = 'storages.backends.s3.S3Storage'
# -------------------------------------------------------------------------